### ISSUE TITLE
there is an error while loading that goes along the lines of cannot load "sf-tile-bonus"(beacon) next-upgradable if flag is set 'not-upgradable'

### ISSUE THREAD

**Issue by Just-A-Programer** [Dummiez/Factorio-StableFoundations#2]
found a solution which is simple: in data-final-fixes just remove the "not-upgradable" flag and it should work.

**Comment by Dummiez** [comment]
This has already been fixed (https://mods.factorio.com/mod/StableFoundations/discussion/6680c9d8a59b7961ff0b79d2) The patch has not been officially released yet but you can hotfix the mod
