### ISSUE TITLE
Suddenly getting a fatal error.

### ISSUE THREAD

**Issue by Alice-Cheshire** [Dummiez/Factorio-StableFoundations#3]
https://i.imgur.com/tkFWfag.png

I've suddenly started getting this error like 20+ hours into a save. It seems to reliably occur now after reloading my latest autosave too. Not really sure what would have caused this to start happening since I haven't updated any mods or Factorio itself since starting this game. My best guess is that I managed to run into some weird edge case that rarely occurs and is more likely to happen with a game like mine where I've got biters attacking my walls literally constantly due to Rampant.

**Comment by Dummiez** [comment]
Should be fixed in the latest version 1.1.1

**Comment by Alice-Cheshire** [comment]
Can confirm, it seems to be working fine now, thanks!
